<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\Ico\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Icon\icon.ico" />
    <None Remove="Resources\Ico\icon.ico" />
    <None Remove="Resources\Intro\intro.mp4" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="LibVLCSharp.WPF" Version="3.9.6" />
    <PackageReference Include="TMDbLib" Version="3.0.0" />
    <PackageReference Include="VideoLAN.LibVLC.Windows" Version="3.0.23" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Ico\icon.ico" />
    <Content Include="Resources\Intro\intro.mp4">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Page Update="MainWindow.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

</Project>
